<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-26T13:10:53 IST" name="Suite" finished-at="2023-07-26T13:11:22 IST" duration-ms="29233">
    <groups>
    </groups>
    <test started-at="2023-07-26T13:10:53 IST" name="Test" finished-at="2023-07-26T13:11:22 IST" duration-ms="29233">
      <class name="eCommercePrjt.Lifestyle">
        <test-method signature="LifestyleTest()[pri:0, instance:eCommercePrjt.Lifestyle@8a589a2]" started-at="2023-07-26T13:11:08 IST" name="LifestyleTest" finished-at="2023-07-26T13:11:11 IST" duration-ms="2821" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at eCommercePrjt.Lifestyle.LifestyleTest(Lifestyle.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LifestyleTest -->
      </class> <!-- eCommercePrjt.Lifestyle -->
      <class name="eCommercePrjt.AirtelTest">
        <test-method signature="Airtel()[pri:0, instance:eCommercePrjt.AirtelTest@2c177f9e]" started-at="2023-07-26T13:10:53 IST" name="Airtel" finished-at="2023-07-26T13:11:08 IST" duration-ms="15126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Airtel -->
      </class> <!-- eCommercePrjt.AirtelTest -->
      <class name="eCommercePrjt.Jio">
        <test-method signature="JioTest()[pri:0, instance:eCommercePrjt.Jio@c65a5ef]" started-at="2023-07-26T13:11:11 IST" name="JioTest" finished-at="2023-07-26T13:11:22 IST" duration-ms="11059" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- JioTest -->
      </class> <!-- eCommercePrjt.Jio -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
